services:
  nosrelay:
    build: .
    ports:
      - "7777:7777"
    environment:
      - RELAY_URL=wss://example.com
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    command: redis-server --loglevel notice
    volumes:
      - redis_data:/data

volumes:
  redis_data: