services:
  nosrelay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - RELAY_URL=wss://example.com
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    command: redis-server --loglevel notice

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    environment:
      - RELAY_URL=wss://example.com
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: "no"