name: Run Tests

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  run_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: ${{ !env.ACT }}  # Skip this step locally if running in Act
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests with Docker Compose
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Check for test failures
        if: failure()
        run: |
          echo "Tests failed, check the logs for details."